#!/usr/bin/env python3
"""
Interactive bounding box annotator for multiple videos using Viser.

Opens a web GUI where you can:
1. Select videos from a dropdown
2. Click to define bounding boxes (top-left, then bottom-right)
3. Save bounding boxes per video
4. Generate a bash script to run track_and_crop.py on all annotated videos
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass, field
from pathlib import Path

import cv2
import numpy as np
import viser


@dataclass
class VideoAnnotation:
    """Stores annotation state for a single video."""

    video_path: str
    frame_rgb: np.ndarray | None = None
    bbox: tuple[int, int, int, int] | None = None  # (x1, y1, x2, y2)
    click_state: list[tuple[int, int]] = field(default_factory=list)  # Temporary clicks


def load_first_frame_rgb(video_path: str) -> np.ndarray:
    """Load the first frame of a video as RGB."""
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    ok, frame_bgr = cap.read()
    cap.release()

    if not ok or frame_bgr is None:
        raise RuntimeError(f"Could not read first frame from: {video_path}")

    return cv2.cvtColor(frame_bgr, cv2.COLOR_BGR2RGB)


def generate_bash_script(
    annotations: dict[str, VideoAnnotation],
    output_path: str,
    smoothing: float,
    crop_scale: float,
    output_dir: str,
) -> str:
    """Generate a bash script with track_and_crop.py commands."""
    lines = ["#!/bin/bash", "# Generated by bbox_annotator.py", ""]

    for video_name, anno in annotations.items():
        if anno.bbox is None:
            continue

        x1, y1, x2, y2 = anno.bbox
        video_path = anno.video_path
        output_video = str(Path(output_dir) / f"{Path(video_name).stem}_cropped.mp4")

        cmd = (
            f'python track_and_crop.py \\\n'
            f'    --video "{video_path}" \\\n'
            f'    --bbox "{x1},{y1},{x2},{y2}" \\\n'
            f'    --output "{output_video}" \\\n'
            f'    --smoothing {smoothing} \\\n'
            f'    --crop-scale {crop_scale}'
        )
        lines.append(f"# {video_name}")
        lines.append(cmd)
        lines.append("")

    script_content = "\n".join(lines)

    with open(output_path, "w") as f:
        f.write(script_content)

    return script_content


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Interactive bounding box annotator for videos"
    )
    parser.add_argument(
        "videos",
        type=str,
        nargs="+",
        help="Paths to video files to annotate",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8080,
        help="Port for viser server (default: 8080)",
    )
    parser.add_argument(
        "--output-script",
        type=str,
        default="run_track_and_crop.sh",
        help="Output bash script path (default: run_track_and_crop.sh)",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="output",
        help="Output directory for cropped videos (default: output)",
    )
    parser.add_argument(
        "--smoothing",
        type=float,
        default=0.8,
        help="Default smoothing value for track_and_crop (default: 0.8)",
    )
    parser.add_argument(
        "--crop-scale",
        type=float,
        default=1.5,
        help="Default crop scale for track_and_crop (default: 1.5)",
    )
    args = parser.parse_args()

    # Validate video paths
    video_paths = []
    for v in args.videos:
        path = Path(v).expanduser().resolve()
        if not path.exists():
            print(f"Warning: Video not found: {v}")
            continue
        video_paths.append(str(path))

    if not video_paths:
        print("Error: No valid video files provided.")
        return

    # Create video names for dropdown
    video_names = [Path(v).name for v in video_paths]

    # Initialize annotations
    annotations: dict[str, VideoAnnotation] = {}
    for name, path in zip(video_names, video_paths):
        annotations[name] = VideoAnnotation(video_path=path)

    # Load first frames
    print("Loading video frames...")
    for name, anno in annotations.items():
        try:
            anno.frame_rgb = load_first_frame_rgb(anno.video_path)
            print(f"  Loaded: {name} ({anno.frame_rgb.shape[1]}x{anno.frame_rgb.shape[0]})")
        except Exception as e:
            print(f"  Failed to load {name}: {e}")

    # Current state
    current_video = video_names[0]

    # Start viser server
    server = viser.ViserServer(port=args.port)

    # Set initial background
    if annotations[current_video].frame_rgb is not None:
        server.scene.set_background_image(annotations[current_video].frame_rgb)
    server.scene.set_global_visibility(False)

    @server.on_client_connect
    def on_client_connect(client: viser.ClientHandle) -> None:
        nonlocal current_video

        # Get current annotation
        anno = annotations[current_video]
        H, W = (anno.frame_rgb.shape[:2] if anno.frame_rgb is not None else (1080, 1920))

        # --- GUI Elements ---

        # Video selector dropdown
        video_dropdown = client.gui.add_dropdown(
            "Video",
            options=video_names,
            initial_value=current_video,
        )

        # Status display
        status_text = client.gui.add_text(
            "Status",
            initial_value="Click top-left corner of object",
            disabled=True,
        )

        # Coordinates display
        coords_text = client.gui.add_text(
            "Coordinates",
            initial_value="Bbox: (not set)",
            disabled=True,
        )

        # Instructions
        client.gui.add_markdown(
            "**Instructions:**\n"
            "1. Click top-left corner of object\n"
            "2. Click bottom-right corner\n"
            "3. Click Save to store bbox\n"
            "4. Select next video from dropdown\n"
            "5. Click Finish when done"
        )

        # Buttons folder
        with client.gui.add_folder("Actions"):
            save_button = client.gui.add_button("Save Bbox", color="green")
            clear_button = client.gui.add_button("Clear", color="gray")
            finish_button = client.gui.add_button("Finish & Generate Script", color="blue")

        # Settings folder
        with client.gui.add_folder("Settings", expand_by_default=False):
            smoothing_slider = client.gui.add_slider(
                "Smoothing",
                min=0.0,
                max=0.95,
                step=0.05,
                initial_value=args.smoothing,
            )
            crop_scale_slider = client.gui.add_slider(
                "Crop Scale",
                min=1.0,
                max=3.0,
                step=0.1,
                initial_value=args.crop_scale,
            )

        # Saved annotations display
        saved_text = client.gui.add_markdown("**Saved annotations:** 0")

        def update_display():
            """Update all display elements."""
            anno = annotations[current_video]

            # Update coords display
            if anno.bbox:
                x1, y1, x2, y2 = anno.bbox
                coords_text.value = f"Bbox: ({x1}, {y1}, {x2}, {y2})"
            elif len(anno.click_state) == 1:
                x, y = anno.click_state[0]
                coords_text.value = f"Top-left: ({x}, {y}) - click bottom-right"
            else:
                coords_text.value = "Bbox: (not set)"

            # Update status
            if anno.bbox:
                status_text.value = "Bbox saved! Select another video or Finish."
            elif len(anno.click_state) == 1:
                status_text.value = "Click bottom-right corner of object"
            else:
                status_text.value = "Click top-left corner of object"

            # Update saved count
            saved_count = sum(1 for a in annotations.values() if a.bbox is not None)
            saved_list = [n for n, a in annotations.items() if a.bbox is not None]
            saved_text.content = f"**Saved annotations:** {saved_count}/{len(annotations)}\n" + \
                                 "\n".join(f"- {n}" for n in saved_list)

        def switch_video(video_name: str):
            """Switch to a different video."""
            nonlocal current_video
            current_video = video_name
            anno = annotations[current_video]

            if anno.frame_rgb is not None:
                client.scene.set_background_image(anno.frame_rgb)

            update_display()

        # Handle dropdown change
        @video_dropdown.on_update
        def on_video_change(_) -> None:
            switch_video(video_dropdown.value)

        # Handle click events
        @client.scene.on_pointer_event(event_type="click")
        def on_click(event: viser.ScenePointerEvent) -> None:
            anno = annotations[current_video]
            if anno.frame_rgb is None:
                return

            H, W = anno.frame_rgb.shape[:2]

            # Get pixel coordinates from normalized screen position
            x_norm, y_norm = event.screen_pos[0]
            x = int(round(x_norm * (W - 1)))
            y = int(round(y_norm * (H - 1)))
            x = max(0, min(W - 1, x))
            y = max(0, min(H - 1, y))

            print(f"[{current_video}] Click at ({x}, {y})")

            if len(anno.click_state) == 0:
                # First click - top-left
                anno.click_state.append((x, y))
            elif len(anno.click_state) == 1:
                # Second click - bottom-right
                x1, y1 = anno.click_state[0]
                x2, y2 = x, y

                # Ensure proper ordering
                if x2 < x1:
                    x1, x2 = x2, x1
                if y2 < y1:
                    y1, y2 = y2, y1

                anno.bbox = (x1, y1, x2, y2)
                anno.click_state.clear()
                print(f"[{current_video}] Bbox set: ({x1}, {y1}, {x2}, {y2})")

            update_display()

        # Handle save button
        @save_button.on_click
        def on_save(_) -> None:
            anno = annotations[current_video]
            if anno.bbox:
                print(f"[{current_video}] Bbox confirmed: {anno.bbox}")
                update_display()
            else:
                status_text.value = "No bbox to save! Click two corners first."

        # Handle clear button
        @clear_button.on_click
        def on_clear(_) -> None:
            anno = annotations[current_video]
            anno.bbox = None
            anno.click_state.clear()
            print(f"[{current_video}] Cleared")
            update_display()

        # Handle finish button
        @finish_button.on_click
        def on_finish(_) -> None:
            saved_count = sum(1 for a in annotations.values() if a.bbox is not None)
            if saved_count == 0:
                status_text.value = "No annotations to save!"
                return

            script_content = generate_bash_script(
                annotations,
                args.output_script,
                smoothing_slider.value,
                crop_scale_slider.value,
                args.output_dir,
            )

            print(f"\n{'='*60}")
            print(f"Generated script: {args.output_script}")
            print(f"{'='*60}")
            print(script_content)
            print(f"{'='*60}\n")

            status_text.value = f"Script saved to {args.output_script}!"

        # Initial display update
        update_display()

    print(f"\nViser running on http://localhost:{args.port}")
    print("Open in browser to annotate videos.\n")

    try:
        while True:
            time.sleep(1.0)
    except KeyboardInterrupt:
        print("\nShutting down...")


if __name__ == "__main__":
    main()
