#!/bin/bash
# Generated by bbox_annotator.py

# website_dance1_subject2_gantree_v2_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/website_dance1_subject2_gantree_v2_part2.mp4" \
    --bbox "1771,808,2167,1590" \
    --output "output/website_dance1_subject2_gantree_v2_part2_cropped.mp4" \
    --smoothing 0.8 \
    --crop-scale 1.5

# website_dance1_subject2_v6_part1.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/website_dance1_subject2_v6_part1.mp4" \
    --bbox "1948,467,2729,1435" \
    --output "output/website_dance1_subject2_v6_part1_cropped.mp4" \
    --smoothing 0.8 \
    --crop-scale 1.5
