#!/bin/bash
# Generated by bbox_annotator.py

# website_dance1_subject2_v3_part5.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_dance1_subject2_v3_part5.mp4" \
    --bbox "2822,1051,3792,2128" \
    --output "motion_tracking_output/website_dance1_subject2_v3_part5_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_dance1_subject2_v4_part10.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_dance1_subject2_v4_part10.mp4" \
    --bbox "809,886,1401,1879" \
    --output "motion_tracking_output/website_dance1_subject2_v4_part10_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_dance1_subject2_v5_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_dance1_subject2_v5_part2.mp4" \
    --bbox "1777,577,2134,1288" \
    --output "motion_tracking_output/website_dance1_subject2_v5_part2_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_dance1_subject2_v6_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_dance1_subject2_v6_part2.mp4" \
    --bbox "2111,510,2586,1381" \
    --output "motion_tracking_output/website_dance1_subject2_v6_part2_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_fight1_subject2_v1_part1.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_fight1_subject2_v1_part1.mp4" \
    --bbox "2117,706,2688,1472" \
    --output "motion_tracking_output/website_fight1_subject2_v1_part1_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \  
     --aspect-ratio '1:3'

# website_jumps1_subject1_v1_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_jumps1_subject1_v1_part2.mp4" \
    --bbox "2484,620,2836,1507" \
    --output "motion_tracking_output/website_jumps1_subject1_v1_part2_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_robustness_test_part1.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_robustness_test_part1.mp4" \
    --bbox "1630,619,2407,1790" \
    --output "motion_tracking_output/website_robustness_test_part1_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_run1_subject2_v1_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_run1_subject2_v1_part2.mp4" \
    --bbox "2958,649,3752,2081" \
    --output "motion_tracking_output/website_run1_subject2_v1_part2_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_subject1_dance1_v1_part5.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_subject1_dance1_v1_part5.mp4" \
    --bbox "1262,655,1776,1711" \
    --output "motion_tracking_output/website_subject1_dance1_v1_part5_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_subject1_dance1_v1_part8.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_subject1_dance1_v1_part8.mp4" \
    --bbox "2511,735,2913,1357" \
    --output "motion_tracking_output/website_subject1_dance1_v1_part8_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'

# website_walk1_subject1_v2_part2.mp4
python track_and_crop.py \
    --video "/home/ANT.AMAZON.COM/benchoi/projects/track_and_crop/motion_tracking_selected/website_walk1_subject1_v2_part2.mp4" \
    --bbox "602,599,1137,1706" \
    --output "motion_tracking_output/website_walk1_subject1_v2_part2_cropped.mp4" \
    --smoothing 0.9 \
    --crop-scale 1.2 \
     --aspect-ratio '1:3'
